### PR TITLE
update security

### LINKED ISSUE #2: Improve authetincation security
Aunthentication tokens are part of the code and that is dangerous. Fix to request user input.

### PR DESCRIPTION
**Pull request by Gonza10V**
input() and getpass() for username and password input in a more secure way. Closes #2

### CODE REVIEW

**Comment by JMante1** [comment]
I agree with the principle here. However it is a temporary function not actually part of the excel converter library. It is probably better to move the entire thing into a test function and to pull the username and password from github secrets for testing purposes.

**Comment by Gonza10V** [comment]
Although I agree that this should be included in the library, I dont know where to put it. We should discuss the architecture of the package to see where to allocate this.

**Comment by JMante1** [comment]
I think you misunderstood. I don't think it should be included in the library package. I think the library should take in a username and password as input but I think the collection of that information should be outside the library e.g. in the wrapper that brings together excel2flapjack and excel2sbol. I think having a way of testing the library with a username and password should be possible but I don't think we should need the user input their either.

**Comment by Gonza10V** [comment]
That is what I need to better understand, how this will be organised to know where to allocate things. The EDC is a wrapper of excel2flapjack and excel2sbol? so that should collect the username and password? how and from where could we collect that information? If we use GitHub secrets how do we connect with that?

**Pull request closed without merging**
